### ISSUE TITLE
Combat skill level selection is only using the display and not the name.

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#1004]
This seems like a bug that was introduced recently. The same issue is happening with weapons master. Here are some screenshots. I can change the Display and that works fine, but I wanted to pass this along.

Combat skill level selection:
![Display name not working 1](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/9976f736-c21d-428c-8db1-a9b2ad016794)

Weapons master selection:
![weapon skill level selection](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/72fd8991-24ab-48ce-9e93-91f6d07d7203)

Also thanks for getting weapons master and deadly blow working. We used it last night and it worked wonderfully!

**Comment by aeauseth** [comment]
@tthomsen please attach the HDC file here so I can use it for testing.  Yes, I reworked all the powers that allow for weapon selection and I obviously broke something.

Nice to hear Weapon Master and Deadly Blow are working well for you!  Always enjoy the positive feedback, most of the feedback we get is related to broken stuff or feature requests.

**Comment by tthomsen** [comment]
Yeah I hear that. Hacking code can be a thankless job especially when all you hear are complaints. So I appreciate all the hard work  everyone is doing. It really makes my life easier as a GM.

This character file should work for all of the issues I submitted. 
[Kwon.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/15394949/Kwon.zip)

**Comment by aeauseth** [comment]
Kwon has a lot going on.  Confirmed the issue you reported.  Also issues with equipment compound powers showing in powers tab instead as under the equipment tab.  Also the CP costs includes equipment (hidden within powers sum), which it shouldn't.  Skills CP calc is off 156 vs 159.  Might tweak the layout so the OTHER tab fits into a single line of tabs.

@tthomsen did you know that you can update the HD file for Combat Luck to have it default to ON.  Hero Designer defaults to "Do not add to Totals", so it uploads with Combat Luck off.  You can change that so it default to ON when uploaded.

**Comment by tthomsen** [comment]
Thanks good to know.

**Comment by aeauseth** [comment]
Fixed.  Also included tooltip as I noticed you have duplicate attack names (block for example).  You should avoid using duplicate names as it may confuse the automatic attack selection.  I recommend adding the word Martial back to your Martial Block, Dodge, etc.

<img src="https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/e6689b01-cc33-495d-b892-bea8cf32c331" height="600"/>
<img src="https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/27d5f0c5-dcf8-464e-8569-c1d5650f560e" height="600"/>
