### ISSUE TITLE
Invisibility cannot be unchecked.

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#1005]
One of my players has been running into this issues. Invisibility can't be unchecked and endurance is not being tracked during combat.

![Invisibility can't be unchecked](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/a9c3a253-0fe5-4473-a8f7-639072bb252f)

**Comment by aeauseth** [comment]
Invisibility now shows up under defenses.  Not technically a defense, but behaves like one.  Confirmed it uses END when token is in the combat tracker. 

TODO: Spend END when it is initially turned on (but not more than once per segment).
TODO: Associate invisibility with invisibility status effect.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/d0e9e54d-91be-4a33-a564-e956de492888)

**Comment by tthomsen** [comment]
Let me know if you need the HDC file.

**Comment by aeauseth** [comment]
Added END use when toggled on.  Also added invisible status if the INVISIBILITY power is based on SIGHTGROUP.

**Comment by aeauseth** [comment]
> Let me know if you need the HDC file.

I do not need an HDC file.  Thanks for offering.

**Comment by tthomsen** [comment]
Excellent, thanks again!
