### ISSUE TITLE
Skill card has all powers checked by default

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#1006]
On the skill card below you can see all of the powers that effect skills are checked by default. Is there anyway these can be unchecked by default? This is more of a quality of life improvement than a major issue.

![Uncheck powers on skill rolles](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/2e977d3f-e3dc-42ef-ae1b-6bd51f5b16ec)

**Comment by aeauseth** [comment]
@tthomsen a HDC file would be handy for this one.  Please attach it here.

**Comment by tthomsen** [comment]
Here you go.
[Taz-Hero.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/15395559/Taz-Hero.zip)
