### ISSUE TITLE
Combat skill level on compound powers cannot be used

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#1007]
Weapons built as compound powers are not using the combat skill levels they are built with. I'm not sure how much of a major issue it would be to fix this, but it would be nice if the CSLs would be included.

The character already has 4 CSLs. Which is what is displayed on the screenshot. However the two from the sword are not being applied. So the total should be 6.
![sword csl](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/9eff4c45-520d-44cc-a948-14b993a1b738)

From hero designer you can see the sword has 2 CSLs:
![Compound powers and combat skill levels](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/e96281c1-6b5f-4812-9d5e-fc745407187a)

However, the weapon's CSLs are showing on the skills tab. For some reason under weaponsmith:
![Compound powers and skills card](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/12e6ea89-27d6-44f8-a574-cd0c41173f1e)

The box is checked, but the CSLs are not being apply to the attack: 
![Sword accuracy](https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/e8ceeb2c-fb5c-42a9-81f3-53f53215bf1c)

Like I said, I'm not sure how much of an issue this would be to fix, but as a stop gap you could always bring back modifying OCV and DCV for the attack power.

**Comment by aeauseth** [comment]
@tthomsen I'm pretty sure I have this fixed.  Mind attaching Rollos.HDC so I can confirm?

**Comment by tthomsen** [comment]
Here you go.
[Rollos.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/15424899/Rollos.zip)

**Comment by tthomsen** [comment]
Let me check on my end. Maybe I'm missing something.

**Comment by tthomsen** [comment]
Good to know. For now we can just add them in manually. As always thank you for everything you do.
