### ISSUE TITLE
Heroroll error with multiple terms

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1012]
Per Archive in discord:

I noticed in the system I can roll /heroroll 3d6[s] to do succuess rolls how do I format it to do a skill roll or attribute roll ?
when I try to do /heroroll 12-3d6[s]
I can an error

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/f6f21b0d-8896-4b19-8961-40be3a808bcc)

**Comment by phBalance** [comment]
Working as expected. This is not functionality that is provided by it. If a user wants to do a success roll then the standard FoundryVTT `/roll` command will do the trick.
