### ISSUE TITLE
Player unable to place template

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1062]
Per Juxtapozblis:

The next is AOE attacks. As the DM, I was able to place it for my player and roll the attack for him, but he was unable to. He got an error message that his token was "not in the scene"

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/a4a741c7-52f5-4375-ad54-a49b7f9a8b01)

**Comment by aeauseth** [comment]
I was unable to reproduce this issue.  Please confirm Blazing Inferno has a token in the cemetery scene.  Is the Blazing Inferno token linked (typically yes for a PC)?  Did the player use the token in the scene to make the attack, or are they using the prototype token in the right sidebar.  Both should work, just trying to get more info.  We may need to get online in discord to chat about this one.

**Comment by AGreaterMonster** [comment]
> I was unable to reproduce this issue. Please confirm Blazing Inferno has a token in the cemetery scene. Is the Blazing Inferno token linked (typically yes for a PC)? Did the player use the token in the scene to make the attack, or are they using the prototype token in the right sidebar. Both should work, just trying to get more info. We may need to get online in discord to chat about this one.

Hi aeauseth! I'm the one who reported it. In the screenshot there, lower left, you can see the token for Blazing Inferno, it has the +5 m text above it. That is the PC and he took this screenshot for me from his computer so i could share it. He was using the token on the scene to make the attack, not the right sidebar. Let me know what other info i can provide, I can reach out to my friend if you have other specific questions. He saw it in his view but it worked fine for me to create that AOE template in the DM view.

**Comment by AGreaterMonster** [comment]
I am probably going to be running the system again with my players this Friday night so I'll have him try it again if possible and share the error log. If that's not enough info, I'm happy to do a discord/chat share with you.

**Comment by aeauseth** [comment]
Did a working session with Juxtapozblis and was unable to reproduce.  Closing issue.
