### ISSUE TITLE
Importing .hdp file

### ISSUE THREAD

**Issue by sevrick** [dmdorman/hero6e-foundryvtt#1067]
So I know how to import a .hdc file but how do you import a .hdp file. Am I not seeing it or is not a feature yet?

**Comment by aeauseth** [comment]
You can't currently import prefabs (*.hdp) files.  I'll add this to the features list.  It would import into the items right sidebar.  From there you could drag them into actors.  This is part of improved in game editing, which is a longer term endeavor.

**Comment by aeauseth** [comment]
A temporary work around: you can create a HDC file with your prefeb items, then drag those items into the item sidebar.

**Comment by sevrick** [comment]
I bought the HSEG HD files from the offical site. They packaged them as a .hdp. What I did was export them as a package then make a new character and  import the package. It's rather convoluted but it works.

**Comment by aeauseth** [comment]
You can now upload HDP files as a compendium.  Feature available in next version (3.0.80).

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/ed570437-de77-4cbe-9dc4-41bddb0d544b)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/3450498e-03d2-4c96-8850-0938669a8c0a)

**Comment by aeauseth** [comment]
@sevrick You can test this yourself after this weekends publish.  Then provide feedback.  You can also upload a HDP file here and I can test it for you, perhaps fixing any issues before this weekends publish.  The HDP file I used for testing was pretty simple.
