### ISSUE TITLE
Moving a compound power into a compendium

### ISSUE THREAD

**Issue by sevrick** [dmdorman/hero6e-foundryvtt#1068]
So I imported a revolver that was a compound power but when I drag it to a compendium it doesn't show any of the contence of the compound power.
What it looks like before copying:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/2902311/d9cde08c-8124-4cdb-a990-c202d251d3ec)
What it looks like after moving it to a compendium:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/2902311/393c7b61-e822-4e2e-9d4d-4c2fe40426c5)

I am trying to create a library of equipment but this is kind of a road block.

**Comment by aeauseth** [comment]
Yes, the compound power is internally converted to individual items, like a multipower.  Foundry doesn't have the concept of a container withing a container.  I'll have to do a bit of research to see how this might be done.

**Comment by aeauseth** [comment]
Possible workaround: Your going to have to move each compound power sub-item into the compendium, then back to your actor sheet.  Not pretty.  A good naming scheme might help.

**Comment by aeauseth** [comment]
Inspiration REF: https://gitlab.com/tposney/itemcollection

**Comment by sevrick** [comment]
This all seems rather technical. To what end is this supposed to do. I pasted it in the console but it just showed this:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/2902311/9c7e4ddc-2681-4074-a602-0bc49ee000fa)
How does this translate into being able to store items in a compendium.

I did however find that you can create a folder drag a compound power into it, then drag the folder into a compendium.

**Comment by aeauseth** [comment]
Sorry about that, I was making some coding notes here, that weren't meant for you.  Your welcome to read along as I try to figure out how to drag/drop compound powers.

**Comment by aeauseth** [comment]
Making some progress.  Items and sub-items are sorted alphabetically by default.  Probably not an issue.  I wasn't intending to use a folder.  Some sort of collapsible UI may be nice.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/67e6d208-11fc-45b6-a8d3-51416b3d34d5)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/0e17e023-8d85-4e2a-81ad-8ddd8d7967c8)

**Comment by sevrick** [comment]
That's awesome! I can't wait to see the final result. Turns out there are a lot of compound powers as weapons in the Hero System Equipment Guide.

**Comment by aeauseth** [comment]
I almost have the compendium working with compound powers as well.  Turns out there is a missing [core FoundryVTT feature](https://github.com/foundryvtt/foundryvtt/issues/8291) that I need for the compendiums, but I can mostly get around that.  I think I can get something working for this weekends publish.  Likely won't be perfect, but better than the current no-support for drag/drop of compound powers.

**Comment by aeauseth** [comment]
Ended up using folders as compendiums were tricky.  This feature will be included in the next release (3.0.80).

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/8dbb1ac5-fc78-4446-a195-6b088d9289f2)
