### ISSUE TITLE
Combat tracker still to be broken I'm getting errors and it won't load the PC characters

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1071]
Archive — Yesterday at 9:10 PM
Combat tracker still to be broken I'm getting errors and it won't load the PC characters

**Comment by AGreaterMonster** [comment]
I'm getting these errors right now trying to test a combat before running a game tonight.

![SCR-20240621-pbnz](https://github.com/dmdorman/hero6e-foundryvtt/assets/121637385/abf2fe8e-b091-48d4-a75e-f4ceb55f397b)

**Comment by aeauseth** [comment]
3.0.77
