### ISSUE TITLE
Killing Attacks too powerful

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1080]
One character with a Martial Killing Attack:

With strength moving from 50 to 80 the killing damage seems to exceed what is allowed. It should likely cap at 4d6+1.

(in Foundry)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/0a84f710-ff07-4944-8258-fead5cde860f)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/4680f20c-1a04-4941-a916-2a1ed273014e)

(in Hero Designer)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/e6ec8e88-3838-4979-b40e-35557353364f)

**Comment by aeauseth** [comment]
I'm unaware of any cap for a HKA or Martial Killing Attack.

**Comment by aeauseth** [comment]
Appears the martial +DC isn't working.

**Comment by phBalance** [comment]
```
I'm unaware of any cap for a HKA or Martial Killing Attack
```
HKA follow the doubling damage rule (p 405 of fred) in 5e. It appears to be an optional rule in 6e (6e book 2 p 99) because why limit yourself.

**Comment by aeauseth** [comment]
![image](https://github.com/user-attachments/assets/5b37b6bc-6986-4eb0-a1dd-c1da17f7d6ca)

![image](https://github.com/user-attachments/assets/f2c5695e-d7c3-485b-9d48-7e7f64459538)
