### ISSUE TITLE
Attack Rolls Always Private

### ISSUE THREAD

**Issue by Chad-Bearsmith** [dmdorman/hero6e-foundryvtt#1108]
The embedded rolls of attack rolls are always private, regardless of how the attack roll is made. For example: I can have the attack roll sent as public, but the embedded roll inside of it is always sent as private. Which isn't a huge issue, but it means only the GM can see the rolls. The players can't even see their own rolls, just that they made one.

This seems to have been a recent change, it wasn't like this a few weeks ago.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/46057286/181f0245-9721-4371-8c60-53b1b7fcb297)

**Comment by phBalance** [comment]
Confirmed. Thanks for the report.
