### ISSUE TITLE
Combat tracker - speed change causes additional post 12 recovery

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1113]
Normal post 12 recovery happens:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/e0f32d3f-62e0-439c-bedd-3385375ecaa2)

The combat moves into turn 2 segment 2 and an attack causes a speed boost which causes a post 12 recovery
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/1383ebff-9f3c-4c1d-9226-01eb6d187873)

**Comment by aeauseth** [comment]
Generic check to prevent Post-Segment 12 running more than once per turn/round.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/19373be9-057a-40b0-8d1a-99ebde4ab8ef)
