### ISSUE TITLE
Reduced Endurance Limitation not working

### ISSUE THREAD

**Issue by sevrick** [dmdorman/hero6e-foundryvtt#1125]
I noticed that powers that have the Reduced Endurance limitation applied and it set to cost 0 END it still cost END when using.

**Comment by aeauseth** [comment]
Hmm, seems to be working fine.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/eab890b7-1512-4f8c-bed9-88fab2a659f6)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/c8ab4482-95f3-4bf7-a9b3-19e67ce43fe2)

**Comment by aeauseth** [comment]
@sevrick send pic of the attack and/or the HDC file.

**Comment by sevrick** [comment]
So I guess what is really happening is a zombie I made has 0 END and when making an attack with this:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/2902311/1ddee75f-ca0f-42eb-ac98-24f86ef89afd)
The zombie takes stun damage because he has no END, which is normal game rules but he shouldn't take stun damage if the attack costs 0 END.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/2902311/0c0e41cd-707d-4658-aba9-ba1405d05808)

**Comment by aeauseth** [comment]
Yup, I see what is going on here.  I can fix that.

**Comment by aeauseth** [comment]
Looks like the automation is following rules as written: `A character who has Reduced Endurance (0 END) on his Hand-To-Hand Attack still has to pay END for the STR he uses with it`.  You aligned with that or am I missing something?

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/56065146-58f8-48ed-a77c-5dbb7345fe09)

**Comment by aeauseth** [comment]
Added prompt to confirm actor wants to USE STUN FOR ENDURANCE

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/67fba34b-9da7-42d5-aa56-1d8448dc53b0)

**Comment by aeauseth** [comment]
Added support for STR with REDUCEDEND.
