### ISSUE TITLE
Stacking DRAINs not working

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1190]
Draining 6 AP from DCV should reduce DCV by at least 1 pt.

![image](https://github.com/user-attachments/assets/bb61a46b-ad23-4c7e-b448-9441fe2fcb29)

![image](https://github.com/user-attachments/assets/2189b9dc-8cbc-4463-aa1a-4b21d09ab899)

**Comment by phBalance** [comment]
Are these adjustment powers from separate attackers?

**Comment by phBalance** [comment]
Also DCV is 5 per value and are defensive so take double if we're talking about 6e if I'm not mistaken. Need to reach the full DCV value to drop it by 1.

**Comment by aeauseth** [comment]
END is a defensive property so should cost double to drain.  Where is the 30 from?

![image](https://github.com/user-attachments/assets/4f1f0f1b-6385-45e3-ac69-2d7b92c36ba1)

**Comment by phBalance** [comment]
As we worked out online ... END, in 6e, is 1/5 per point and is a double defense cost characteristic. So 12 AP of END drain is 60 points of END, divided by 2 gives 30 which is correct.
