### ISSUE TITLE
Combat tracker does not show tokens for players (I think the GM sees it)

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1199]
This is what a player sees:
![image](https://github.com/user-attachments/assets/eb9d0f58-06aa-4515-b35f-e4f5ac17a23e)

This is a likely related console error/crash.
![image](https://github.com/user-attachments/assets/27db3f06-ebc0-47b1-8de6-96f3daeef873)

**Comment by aeauseth** [comment]
When GM adds new tokens to combat tracker, players don't see the additional tokens.  `game.combats.active.combatants` shows the same number of combatants, so possibly a UI issue.  Refreshing browser seems to resolve the issue.

**Comment by phBalance** [comment]
Proposed solution had some issues, moving back to open
