### ISSUE TITLE
Hold action not implemented

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1206]
... so people have to manually track the segment order.

**Comment by aeauseth** [comment]
REF: #608

**Comment by aeauseth** [comment]
Added new "holding" status that looks like a clock.  Right clicking a token allows you to enable the "holding" status.  The combat tracker shows "holding" status with a yellow background.  Holding status automatically end when token next phase starts.

![image](https://github.com/user-attachments/assets/e797ccfd-cd25-45fd-9de1-eb3211ac2deb)

![image](https://github.com/user-attachments/assets/7ddb8fa5-6050-4a44-9693-7999b5fefede)
