### ISSUE TITLE
Active Point discrepancy entangle

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1230]
![image](https://github.com/user-attachments/assets/e933b1c7-bad1-4cef-9262-96e45b50f5c6)

**Comment by phBalance** [comment]
This is rather gross. The ADDITIONALED and ADDITIONALPD adder levels have to be added together and then as a sum evaluated against the cost of 3 for 1 and 5 for 2. There's no pretty way to handle it in `calcBasePointsPlusAdders`.
