### ISSUE TITLE
Strength rolls should use endurance

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1253]
Rolled STR (full) with negative end, should do STUN damage ... no END used for the roll. No other characteristics rolls should use endurance presumably.

Remember that strength usage only happens once per turn which is why when using strength to escape from an entangle it makes sense to use casual strength first and then use full strength as an action.

**Comment by aeauseth** [comment]
We do not track the max STR use per phase, so it is possible to pay END twice+ for using STR.
