### ISSUE TITLE
character sees only swimming movement

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1293]
Might to do with somehow getting negative distance movements should show something when movement is negative (was accidentally changed on character sheet).

![image](https://github.com/user-attachments/assets/f7d46d91-d99a-4bfc-a4df-6740a867a61f)

**Comment by aeauseth** [comment]
was NEGATIVE values for other movement types.  No bugs here.

**Comment by aeauseth** [comment]
Turns out the toggles were subtracting values instead of adding.  Fixed issue/confusion with Active Effects and onActiveEffectToggle.
