### ISSUE TITLE
Damage Resistance gets confused by extra PD (likely 5e only)

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1297]
With +7PD on and off it is giving double the PD

![image](https://github.com/user-attachments/assets/25773eee-e8a4-4c7f-bc74-634acd75ac58)
![image](https://github.com/user-attachments/assets/ba1f7ebc-3175-4e68-b4c8-79eb9885f8d4)

**Comment by aeauseth** [comment]
HD shows 7 rPD.  Foundry shows 3 rPD.
![image](https://github.com/user-attachments/assets/25af1512-aa4d-4d50-8398-bebbd227e6d7)
![image](https://github.com/user-attachments/assets/4392b00d-7b4b-4189-a224-5755100ec36a)
![image](https://github.com/user-attachments/assets/f072a203-01c6-42b8-8a89-ad27213f8112)
![image](https://github.com/user-attachments/assets/89c1712f-7ac5-4a23-a425-e2bb127e19c8)

**Comment by aeauseth** [comment]
Added check to make sure PD/ED that were added to VALUE as an AE weren't added a second time.
![image](https://github.com/user-attachments/assets/f0ff9e9c-e938-43c2-85ca-b2048f88a189)
