### ISSUE TITLE
Explosion AOE damage incorrect

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1323]
Warlock is 14m from center of AOE.  11 dice over a 16m explosion.  So Warlock should have taken at most 2 dice of damage. Also I thought the damage dice was supposed to be sorted, highest at center, lowest at edge of template.

![image](https://github.com/user-attachments/assets/4ec8be8f-8cfe-4dbd-bf72-8e5445f1f428)

![image](https://github.com/user-attachments/assets/2883e663-91aa-46e9-b8d0-9771232b2ad0)

![image](https://github.com/user-attachments/assets/d64ea497-8d28-401b-a3ce-052b1496aa23)

![image](https://github.com/user-attachments/assets/16bd8e52-426f-41b9-a420-7d76e618454d)

![image](https://github.com/user-attachments/assets/24649ff2-2981-441a-b385-cd916976447b)

**Comment by phBalance** [comment]
Works for individual damage application but doesn't work for the "Apply Damage to ALL" button as that applies as if everyone were at the epicentre of the explosion. Works for non explosion AoE but not for the situation where things need to be applied differently to each target.

**Comment by phBalance** [comment]
Resolved in #1326
