### ISSUE TITLE
Collapsible Equipment Entries and Inventory Containers

### ISSUE THREAD

**Issue by sevrick** [dmdorman/hero6e-foundryvtt#1357]
I noticed that looking at the equipment is very cluttered, as is the nature of the Hero System. This is especially true when you get into compound powers.

I was thinking that being able to collapse to where just the name and the power of the equipment shows, would make it much cleaner and more visually appealing.

Also in the same vein the ability to make a piece of equipment count as a container. 

For example I have made a backpack item. I imported it and dragged it onto a character. However there is no way to show what items I have that are in the backpack much like other systems.

If there was a box I could check that said something like "Is a Container" it would allow me to drag and drop items onto it to show it is in that container. And possibly be collapsible. You could even have check box at the top which would allow you to equip and unequip the backpack then have the weight totals change accordingly.

**Comment by aeauseth** [comment]
Simple implementation.  Stores collapse/expand state it item database, so state is the same for everyone.

![image](https://github.com/user-attachments/assets/f0e83d73-5488-4124-812b-2e78d3f2709c)
![image](https://github.com/user-attachments/assets/f3803b5e-1b84-4ff1-8ff6-cd712ed3703d)

**Comment by aeauseth** [comment]
There is room for improvement.  Keeping collapse/expand state local to client instead of in item db would allow player to collapse, yet GM to keep expanded.  A css animation showing the collapse/expand would greatly improve the user experience.

**Comment by aeauseth** [comment]
You can drag items into and out of a container.  You cannot drag containers into or out of other containers (list a compound power into or out of a framework).

**Comment by aeauseth** [comment]
When you drag skills out of a compound power, they show up in the SKILLS tab and there is no way to put them back.

**Comment by aeauseth** [comment]
> Will collapsing work with nonmulti-powers?

No. Per discord: This will not collapse the description of an induvial power/item.

![image](https://github.com/user-attachments/assets/d9e8c1ac-7d0a-4da2-8cf1-f35028ada2e6)
