### ISSUE TITLE
Roll to Hit OCV and DCV modifiers not working

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#137]
OCV is pretty straight forward.  DCV should be an Active Effect that expires.

![Screenshot 2023-06-16 235159](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/50c2f5c2-d633-435a-ab73-d040e9a91a1e)

**Comment by AGreaterMonster** [comment]
<img width="920" alt="SCR-20230625-bcjz" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/121637385/67ec1640-0888-4ad7-9963-9eeaab4f641e">

I think this is a related issue. I uploaded my first character .HDC and the OCV and DCV are stuck at 0 and 0 on the character sheet.

**Comment by aeauseth** [comment]
> I think this is a related issue. I uploaded my first character .HDC and the OCV and DCV are stuck at 0 and 0 on the character sheet.

Hey @AGreaterMonster, would you mind uploading your HDC file here so I can do some additional testing?  Also have you tried with Foundry v11 and 3.0.0-alpha (or later)?

**Comment by AGreaterMonster** [comment]
Hey! I ended up deleting those tokens and adding new characters from scratch and that seemed to fix it. And also now updated to 3.0.0! As I'm setting up my first campaign and testing running combat for the first time, I'll post bugs if i find any. Thanks for your contribution to this!!!

**Comment by aeauseth** [comment]
> Hey! I ended up deleting those tokens and adding new characters from scratch and that seemed to fix it. And also now updated to 3.0.0! As I'm setting up my first campaign and testing running combat for the first time, I'll post bugs if i find any. Thanks for your contribution to this!!!

You should not have to delete the tokens, re-uploading the HDC file usually does the trick!
