### ISSUE TITLE
CSLs were showing on the to hit card, but weren't in the formula for an AoE attack

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1392]
![image](https://github.com/user-attachments/assets/b4217b72-8bf0-4e04-8fb0-159b4a8bb915)
![image](https://github.com/user-attachments/assets/ffcd4ecd-1218-49d9-b9a5-39e265d1c320)

**Comment by aeauseth** [comment]
Fixed: 
![image](https://github.com/user-attachments/assets/b3ec6e6c-b33b-4853-93d3-1dff6ed4cd01)
