### ISSUE TITLE
The drag ruler range is 32m (-4 penalty) but the computed range penalty is -6 for the attack 

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1397]
![image](https://github.com/user-attachments/assets/e3154669-df63-4662-9543-d069fd6a581a)

![image](https://github.com/user-attachments/assets/b7f638c4-08d1-4e83-9a90-e2c974ff56d0)

**Comment by aeauseth** [comment]
There are 2 warlock tokens in the scene and were picking the wrong one.  We need to pass the token in the attackAction

**Comment by aeauseth** [comment]
Use controlled token as an indicator of which token to use (when there is more than one).  An additional upgrade would be to pick the closest token to the target (which is also just a guess).

```js
        // Educated guess for token
        const token =
            actor.getActiveTokens().find((t) => canvas.tokens.controlled.find((c) => c.id === t.id)) ||
            actor.getActiveTokens()[0];
```
