### ISSUE TITLE
Knockback seems to think that a character is in the air when they have no movement powers active that are related.

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1400]
![image](https://github.com/user-attachments/assets/162e993d-8c19-42bd-8713-c882f5d704ab)
![image](https://github.com/user-attachments/assets/0b007ed9-7062-4c20-9dec-0fb398373bce)

**Comment by aeauseth** [comment]
Added check to make sure FLIGHT is turned on.
