### ISSUE TITLE
Nightvision costs 5 pts

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1404]
![image](https://github.com/user-attachments/assets/54dbb1a6-f138-4655-ae00-117dee24d91e)

**Comment by phBalance** [comment]
On the surface appears to be a character loading race condition. Can edit the power's name and it will display the correct value. Load again and it will appear with the correct cost.

The same problem seems to be happening with other sense powers (and potentially other powers?)

**Comment by aeauseth** [comment]
Fixed with vision rework.
