### ISSUE TITLE
Would be nice to have TK show the distance something can be thrown

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1450]
![image](https://github.com/user-attachments/assets/6901981b-2837-47f9-aa72-5ae72a913c4e)

Would be able to roughly figure out how much something would weigh. Then subtract that weight from the strength and compare on throw table.

**Comment by aeauseth** [comment]
![image](https://github.com/user-attachments/assets/06bb1e24-81a8-4ea0-ab15-38138ad679ff)
