### ISSUE TITLE
AoE on STR doesn't calculate END use correctly

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1460]
Onyx for reference:

![image](https://github.com/user-attachments/assets/80fe38fe-6dcd-4462-af7a-450f67e87204)

**Comment by aeauseth** [comment]
item.system.usesStrength = false

**Comment by aeauseth** [comment]
Closing as this it isn't really a bug.  Will add a feature request in the future to provide naked advantage support.
