### ISSUE TITLE
Setting characteristic's max to less than core is not showing a red cell

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1461]
![image](https://github.com/user-attachments/assets/90bf6b26-4419-455e-a04f-9d7ca4ea7d1b)

**Comment by aeauseth** [comment]
![image](https://github.com/user-attachments/assets/17a30bfb-86b6-43ee-be64-6a6ff185f98f)

**Comment by aeauseth** [comment]
A bit strange for flight, but not sure it is worth making exceptions for movement powers.
![image](https://github.com/user-attachments/assets/85016020-6918-402d-8e62-9da4c0fc1ba3)
