### ISSUE TITLE
Not attacking the entangle does actually attack the entangle

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1500]
Warlock was entangled with a Entangle that is supposed to be transparent to PD attacks.
A creature then performs a physical attack and is forced to attack the entangle but somehow destroys the entangle.

![image](https://github.com/user-attachments/assets/9e054280-25f3-49a4-9e12-c12a2d72b3e5)

![image](https://github.com/user-attachments/assets/f4782375-89a2-4b29-9712-6b90fd6326d6)

(see https://github.com/dmdorman/hero6e-foundryvtt/issues/1499 for the other bug)

**Comment by aeauseth** [comment]
If you forget to target the token and/or use "Apply Damage" then you will get this prompt: 
![image](https://github.com/user-attachments/assets/74496a31-f034-42f7-99a8-ce4ddb2d49d1)

Also, the default targeting of entangles is UNCHECKED when the ENTANGLE has TAKESNODAMAGE.
