### ISSUE TITLE
Crossbow Multipower doesn't have all powers showing in the chat card for actor description

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#1504]
Might be that the perceivability code is not respecting the parent OAF for the multipower
![image](https://github.com/user-attachments/assets/420be4dc-1d19-47d9-9c55-94e9a5fc895e)

![image](https://github.com/user-attachments/assets/9ef06502-03d5-4d7b-b5d9-011a6a87aead)

![image](https://github.com/user-attachments/assets/95b0ab96-e0d3-4837-8d75-ba999d25e961)

Also notice that the bayonet has OAF x2

**Comment by aeauseth** [comment]
![image](https://github.com/user-attachments/assets/ea6349a0-dae1-49e8-98fd-94b41bdb4fbf)
