### ISSUE TITLE
Shrinking: extra KB is only for distance not damage

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1544]
Need to confirm this rule.

**Comment by phBalance** [comment]
Confirmed in 5e (FReD 218) and 6e (6eV1 281).

**Comment by aeauseth** [comment]
![image](https://github.com/user-attachments/assets/ad00e6a7-7075-4639-b596-64dcb5852116)

![image](https://github.com/user-attachments/assets/de0b3c91-9b17-4b67-84e9-737f7cfe22ac)
