### ISSUE TITLE
Powers active when unchecked, inactive when checked

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#162]
Using Foundry v11.302, HERO system 3.0.0-alpha.

Steps to reproduce:

1. Create new PC.
2. Import Streak.hdc (see attached zip file).
3. In the Attacks tab, roll the "Flurry Of Blows I" attack. It lists the Effective Strength of 65. This is incorrect.
4. In the Powers tab, click on the Active box for "21) Push It! Push It Good!". It unchecks and immediately rechecks itself.
5. Roll the "Flurry Of Blows I" again, this time the Effective Strength is 20. This is the correct value.
6. Uncheck the Active box for "21) Push It! Push It Good!".
7. Roll the "Flurry Of Blows I" attack. It lists the Effective Strength of 65. This is incorrect.

[Streak.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/11861175/Streak.zip)

**Comment by aeauseth** [comment]
All powers default to ON.  **Push It! Push It Good!** is adding STR+45.   20+45 = 65 STR.  I see there is a totaling options dropdown.  Perhaps I can use that to default the power to off.

![Screenshot 2023-06-25 163432](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/ea26d946-1daa-45b3-a71c-6c29fd4c5c54)
![Screenshot 2023-06-25 163856](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/9f18f382-2071-4244-bf22-ad74cdd3870a)

![Screenshot 2023-06-25 163945](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/f9615e6d-8e4c-40f8-b628-ed0fe7130bd5)

**Comment by aeauseth** [comment]
Confirmed the toggles are glitchy.

**Comment by aeauseth** [comment]
Fix will be included in 3.0.1-alpha release.
