### ISSUE TITLE
Combat Tracker

### ISSUE THREAD

**Issue by GooseThatCould** [dmdorman/hero6e-foundryvtt#24]
Hi, I don't know if this is me being really dumb or not, but in the v10 version of the system, pressing the "start combat" button in the combat tracker does nothing. The participating combatants are added to the tracker perfectly fine, and the system does a great job of ordering them according to speed and dexterity, but the actual combat refuses to begin for some reason. Maybe its me being dumb, which if it is, let me know so I can get it working. Thanks.

**Comment by techogre** [comment]
Can confirm.

**Comment by RPMiller1** [comment]
I can also confirm. Just tried it tonight.

**Comment by dmdorman** [comment]
Sorry just now saw this! It should be fixed now. Try updating to the latest release :)

**Comment by GooseThatCould** [comment]
I just did, and it works! Thanks a lot for the fix, its really helpful because my players sometime argue what turn we're on for the sake of recovery, haha. Great work, and much appreciated!
