### ISSUE TITLE
Marking a token as dead marks all identical tokens as dead.

### ISSUE THREAD

**Issue by GooseThatCould** [dmdorman/hero6e-foundryvtt#247]
Hi,
Ignore if this isn't a system problem but an issue with something else, but I haven't been able to replicate on the DnD5e module.
What is happening is that if you drag out multiple tokens of the same thing (like a bunch of goons) and mark one of them as dead, they all immediately are marked as dead. 
My apologies if it isn't the fault of the system but some other issue that I've managed to run into.
Thanks!

**Comment by aeauseth** [comment]
You need to turn off *Link Actor Data* in the actor Prototype Token or Token screen.
   - Named actors can have tokens on several scenes, and by default their properies are linked to the master actor.  So as you move from scene to scene their STUN/BODY/Statuses and all other properties remain the same.
   - Generic actors should have their link actor data unchecked, which allows you to make distinct changes to the tokens, those changes do not affect the master actor.  You may find [Token Mold](https://foundryvtt.com/packages/token-mold) useful to rename generic actors.
![bitmap](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/0eb55539-e6eb-4cdb-a507-2de791f5fba5)

**Comment by GooseThatCould** [comment]
Thank you, I appreciate the explanation with pictures, everything is great on my end.
