### ISSUE TITLE
Combat tracker does not work

### ISSUE THREAD

**Issue by RPMiller1** [dmdorman/hero6e-foundryvtt#28]
I have upgraded to 2.0.2 and I cannot get the combat tracker to work at all. I'm not sure if I'm doing something wrong, but the actors are not imported into the proper phases and there is no way to start the encounter. The tracking also appear to be broken or not working. I noticed that after importing an HDC file, it isn't taking the correct CV from the file either. It appears to be staying on the default of 3 even though other characteristics are updated.

**Comment by RPMiller1** [comment]
Also, none of the powers or martial maneuvers are being imported either.

**Comment by dmdorman** [comment]
2.0.2 should have addressed the combat tracker issue. 

Can you give me the steps to reproduce the behavior you're seeing?

**Comment by RPMiller1** [comment]
So, I have all the actors imported with the HDC files. I have added them to the scene. I the "+" to create a new encounter, and I see a list of all 12 phases, but that's it. No actors are added to the phases, clicking the arrows at the bottom only jump through the turns rather than the phases. I get nothing.

As for the powers and maneuvers, I import the HDC file and I get the characteristics and skills populated, but no powers are martial maneuvers are populated. At a minimum, I would have expected all the standard maneuvers to be in there, but there is nothing.

**Comment by dmdorman** [comment]
Have you added the actors to the combat? 

Right click on them from the scene and then click the sword and shield icon on the the bottom right

**Comment by RPMiller1** [comment]
Ah! That's what I was missing. D'oh! Okay, so now I'm back to the characteristics not being imported properly from the HDC file. As I started cycling through the phases, I found that it wasn't including everyone that should have an action, so I'll need to look at the sheets again and fix those.

**Comment by dmdorman** [comment]
I'll close this issue then and use #29 to discuss the importing errors
