### ISSUE TITLE
Upload .HDC button not working properly

### ISSUE THREAD

**Issue by dmdorman** [dmdorman/hero6e-foundryvtt#29]
Also, none of the powers or martial maneuvers are being imported either.

_Originally posted by @RPMiller1 in https://github.com/dmdorman/hero6e-foundryvtt/issues/28#issuecomment-1457092665_

**Comment by RPMiller1** [comment]
As for the powers and maneuvers, I import the HDC file and I get the characteristics and skills populated, but no powers are martial maneuvers are populated. At a minimum, I would have expected all the standard maneuvers to be in there, but there is nothing.

**Comment by dmdorman** [comment]
Could you attach the .HDC file you're using?

**Comment by dmdorman** [comment]
The upload button definitely needs some rework. Hopefully I'll be able to get to it tonight

**Comment by RPMiller1** [comment]
All 6 of them?

**Comment by dmdorman** [comment]
Just one will work

**Comment by RPMiller1** [comment]
It won't let me attach HDC files here, so just a moment while I zip them up.
[Combatants.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/10903685/Combatants.zip)

**Comment by RPMiller1** [comment]
Sorry, gave you all 6. I did notice inconsistencies when uploading them, so you might want to try them all anyway.

**Comment by dmdorman** [comment]
Thanks!

**Comment by dmdorman** [comment]
I believe this is addressed by changes I made in 2.0.4

Something to be aware of is the 'powers' type items are broken right now and will require a rewrite. My suggestion for powers is to create the item separately and then drag it onto the character sheet. 

You can create the item from the upper right hand side. Its the icon in-between the person and book icons. Then choose 'power' for type. 

Then open the desired actor sheet and you should be able to drag the power from the right hand side to the actor sheet

**Comment by RPMiller1** [comment]
I just tried uploading 6e versions of two of the characters and I got this error:
![image](https://user-images.githubusercontent.com/29924417/223499242-2a3f044c-5e85-4af1-9ddb-2624d8f3a829.png)
[6thEdition.zip](https://github.com/dmdorman/hero6e-foundryvtt/files/10912107/6thEdition.zip)
I've attached the two files causing the problem. The other ones do not appear to be causing this error.

**Comment by dmdorman** [comment]
I know what causes this. Should be able to fix tonight

If you want to get around this you can edit those characters in Hero Designer and make sure every power/perk/talent/etc has a name defined. Though this is definitely a bug in how the Upload .HDC button handles things

**Comment by RPMiller1** [comment]
No worries. I'm not in a rush, so I can wait.

**Comment by dmdorman** [comment]
looks like this was probably caused by the blank spaces in the the .HDC file. Didn't know you could do that lol. 

The error message in this case seems like nothing to worry about. Setting a release that should suppress this message.

**Comment by dmdorman** [comment]
Up next would be either a power item rework or actor sheet redesign

**Comment by RPMiller1** [comment]
Either one would be great, but I think the power item would be more useful, but likely more work I'm sure. Actually, as I think about it, what would be really awesome would be to automatically include all the default maneuvers in the actor sheet. That would be great especially for new players. I'm introducing my son's group to the system and using your module to make it as easy as possible and having all those default maneuvers would be a huge boon. But I'm guessing that would still be a lot of effort because you would likely need to still incorporate all the martial maneuvers to make it fully functional?

**Comment by dmdorman** [comment]
The default maneuvers should be there (unfortunately only after uploading a .HDC file). If their missing that's a bug lol. You should also be able to add optional maneuvers by changing the settings and doing a .HDC upload again. 

Yeah I need to move the martial maneuvers stuff over with the default maneuvers.

The bug with the power type items has to do with editing the items from the actor sheet directly. You should still be able to create powers on the right hand side, but Uploading .HDC files won't get you any of the automation that comes with building out the item.

**Comment by RPMiller1** [comment]
Okay. I'll take a look at that again and see if they are there now, and let you know. I'll also look into building the items. I'm new to Foundry as a VTT as well, so I'm learning it at the same time I'm trying to get the Hero functionality. I've seen Hero System APIs written in java in other VTTs, so I get what a massive undertaking it is and appreciate all the time you've invested.
