### ISSUE TITLE
Unable to update to 2.0.3

### ISSUE THREAD

**Issue by RPMiller1** [dmdorman/hero6e-foundryvtt#30]
Just tried updating to 2.0.3 and it gets to 100% and then it just spins forever. Closing and reopening shows it still at 2.0.2.

**Comment by Mozmonar** [comment]
Same issue for me.

**Comment by dmdorman** [comment]
my bad, accidentally put in a bad link. Can you try again? This time 2.0.4 :)

**Comment by Mozmonar** [comment]
Worked this time!
