### ISSUE TITLE
Adding Strength to an Attack concatenating rather than adding

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#31]
When an attack has the "Uses Strength" box checked, the final damage is a concatenated value rather than an added value. For example, Averageman is STR 20. When his hits with his Averagemelee attack (+7d6 hth) the damage is listed as 72d6.

**Comment by dmdorman** [comment]
Thanks for reporting. I believe this is fixed in the most recent release

**Comment by techogre** [comment]
Confirmed fixed in 2.0.6,

Thank you for your continued hard work.
