### ISSUE TITLE
Lightning Reflexes are not being properly added to Dex for turn order

### ISSUE THREAD

**Issue by RPMiller1** [dmdorman/hero6e-foundryvtt#32]
As the subject says, Lightning Reflexes' bonus DEX are not being added in when the action order is being created.

**Comment by dmdorman** [comment]
Right now there is nothing that takes Lightning Reflexes into account for turn order, but I am interested in adding it. 

That would only apply to a specified action correct?

**Comment by RPMiller1** [comment]
From the rules:
A character can purchase Lightning Reflexes to affect **all** of his Actions, a **group** of Actions, or a **single** Action. The cost is indicated on the accompanying Lightning Reflexes Table.
When a character uses Lightning Reflexes to increase his effective DEX, he may only execute the specific Action or maneuver he purchased Lightning Reflexes for. For example, if a character has +4 Lightning Reflexes that only work with his Defensive Strike, he may only use his Defensive Strike (no movement, acrobatics, or other Actions) in a Phase when he uses the +4 effective DEX.

**Comment by dmdorman** [comment]
Lightning reflexes have been added to the combat tracker. Please let me know if it looks correct rules wise. Haven't had a campaign that uses lightning reflexes yet

**Comment by RPMiller1** [comment]
I'll check it tomorrow. Have you joined the Hero System Discord? There's a Foundry VTT channel there. That would be a great resource for testing for you as well.

**Comment by dmdorman** [comment]
Yeah I joined it recently
