### ISSUE TITLE
Strength not being added correctly to attacks

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#33]
Characters are not doing 1d6 per 5 STR. I tried a few STR values and here are the results:

STR = is xd6 = should be yd6
0 = 0d6 = 0d6
5 = 0d6 = 1d6
10 = 0d6 = 2d6
15 = 1d6 = 3d6
20 = 2d6 = 4d6
25 = 3d6 = 5d6
30 = 4d6 = 6d6
etc.

It looks like 10 is being subtracted from the STR value at some point.

**Comment by dmdorman** [comment]
Looks like I misunderstood the rules. I took "STR has a Base Value of 10; each additional +1 point of STR costs 1 Character Point. Every +5 Character Points represents +1d6 damage" (From Hero 6th Volume 1 page 41) to mean every 5 points after STR 10. 

This should be an easy fix.

**Comment by techogre** [comment]
2.0.0.7 fixes this issue
