### ISSUE TITLE
Attack "Roll to Hit" dialogue"Effective Strength" default value incorrect

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#34]
When an attack has the "Uses Strength" box checked the "Roll to Hit" dialogue does not list the current strength as the default "Effective Strength". It can be changed manually, but it should default to whatever the current STR value is. 

For example, a character has received a boost in STR from 20 to 30. The current STR is now 30, however, in the "Roll to Hit" dialogue, the "Effective Strength" is still listed as 20.

**Comment by dmdorman** [comment]
Looks like this was caused by the 'Roll to Hit' pop out getting the strength of the base actor instead of the token actor.

**Comment by techogre** [comment]
2.0.0.7 fixes the isue
