### ISSUE TITLE
Killing Attacks using Strength not calculating correctly

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#36]
When an attack is designated as a Killing Attack and the Uses Strength box is checked, the system is adding dice as if it was a normal attack. For example, a 2d6 killing attack that uses 20 Strength is listed as a 6d6 killing attack, it should be a 3d6+1 killing attack

Strength based bonus damage for killing attacks should be:

STR = extra killing damage

0 = 0
5 = +1
10 = +1/2d6
15 = +1d6
20 = +1d6+1
25 = +1-1/2d6
30 = 2d6
etc

**Comment by dmdorman** [comment]
fixed as of V2.1.3-alpha
