### ISSUE TITLE
Adding characteristics with a power

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#37]
There should be a way to add to Characteristics through a Power, in addition to Skills, Manoeuvres, etc.

For example, a speedster uses a Variable Power Pool for "Speedster Tricks", and one trick is to Dodge, adding +5 to DCV (cost END so it's not always "on"). Right now, the player has to manually update the DCV on the sheet.

**Comment by dmdorman** [comment]
Added as of v2.1.3-alpha
