### ISSUE TITLE
Turning powers on or off

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#38]
There should be a way to turn a power on or off, especially when using a VPP or Multipower. Ially, a check box in the left most column would work. If it's checked, the power adds its attacks/skills/what have you and any END use is used at the end of the phase. If it's not checked, it's ignored.

**Comment by dmdorman** [comment]
That's a good idea. I'll add when I re-work power items

**Comment by techogre** [comment]
I apologize for spamming, I'm just seeing issues and putting them up there to be dealt with at your leisure. I used to be a developer and the QA tick is still strong in me. :)

**Comment by dmdorman** [comment]
No worries, glad someone is using the system!

**Comment by aeauseth** [comment]
As of v2.1.3-alpha.  Powers related to characteristics can be toggled on powers tab.  Many defensive powers are copied to the defense tab, which can be toggled.  So this is partially resolved.

**Comment by aeauseth** [comment]
v2.2.0-alpha improves the ability to turn powers and equipment on/off.  I believe movement is the only thing left.
