### ISSUE TITLE
entangle incorrect cost calculations

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#389]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/d2c881b3-ce4f-467b-9e56-cd905e7a6b35)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/8530cc56-39b4-4748-84f3-b68c5782e93f)

**Comment by phBalance** [comment]
Correct now:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/27e5df9b-6a60-4807-950c-05020ac54e17)
