### ISSUE TITLE
Change default Cone area effect angle from 53 degrees to 60 degrees

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#40]
The default angle of the cone template in Foundry is 53 degrees. HERO assumes a 60 degree cone. This can be changed in the world data. Here is a link to an example "Setting the default angle of a cone template":  https://foundryvtt.wiki/en/basics/world-scripts

**Comment by dmdorman** [comment]
should be added as of v2.1.2-alpha
