### ISSUE TITLE
HDC Import issue - 6e - some default characteristics set to zero

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#430]
Foundry Virtual Tabletop:   Version 11 Stable
Build:   313
Hero System 6e (Unofficial) v2:   3.0.48
Active Modules:   2 (Drag Ruler 1.13.8, socketlib 1.0.13)

The calculated characteristics in 5e are treated as a base of zero in 6e. For example, importing a blank character will set SPD to zero, 

The following characteristics are set to incorrect values:

SPD, PD, ED, REC, END, STUN = 0
RUNNING = 6
SWIMMING, LEAPING = 2

If I set the characteristic to a different value in HERO Designer (e.g. SPD 3), the resulting characteristic is raised or lowered from the incorrect default values (e.g. SPD 1 in this case).

It's as if the value for those characteristics are expected to be calculated rather than a set characteristic but defaults to zero when a 6e sheet is being used. (e.g. SPD was calculated in 5e and set to a base of 2 in 6e)

To recreate:

1. In Hero Designer, create a new 6e superheroic character.
2. Add a  Character Name.
3. Save the character.
4. Create a new blank character and import into Foundry.
5. The old calculated 5e characteristics are all off in non-calculated 6e.

**Comment by techogre** [comment]
It was tested with a 5e Superheroic character. It imports without issue.

**Comment by aeauseth** [comment]
Created quench test. Confirmed there are issues.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/06c7f9f4-ba5d-410c-bd18-0e30a5a2a7c8)
