### ISSUE TITLE
6e - Boostable charges not supported.

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#432]
Foundry Virtual Tabletop:   Version 11 Stable
Build:   313
Hero System 6e (Unofficial) v2:   3.0.50
Active Modules:   2 (Drag Ruler 1.13.8, socketlib 1.0.13)

6e test character uses bootable charges. There is no option/dialogue to boost an attack.

**Comment by aeauseth** [comment]
Confirming that BOOSTABLE charges are not currently supported.

**Comment by aeauseth** [comment]
Initial support for BOOSTABLE CHARGES.  Associated burnout is not implemented.  Does not account for reducing the +DC increase for powers with advantages.
