### ISSUE TITLE
Mental Blast rolled 4 damage but dealt 3 damage.

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#435]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/8539878e-378d-44b1-ac8a-274ce4c3454b)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/ee3578ea-dca0-46da-abde-375838ae781e)

**Comment by phBalance** [comment]
Likely the same as #508. The root cause of that is not correctly treating `roll.terms` when it has more than 1 term (i.e. code is generally using `roll.terms[0]`).
