### ISSUE TITLE
Resistant Def w/ Activation Roll does not automate activation  roll

### ISSUE THREAD

**Issue by Kamarathin** [dmdorman/hero6e-foundryvtt#457]
Character has body armor with Activation Roll 14-. Activation not taken into account and Res Def is considered to be active unless manually unchecked prior to applying damage.

**Comment by aeauseth** [comment]
REQUIRES A ROLL rules say `By default, the character must attempt the roll only when activating the power (i.e., whenever he uses an Instant Power, or when he first turns on a Constant or Persistent Power).  If he must attempt the roll every Phase he maintains or uses a Constant or Persistent Power (such as a Defense Power where he must succeed with the roll whenever he needs to apply that defense against an attack), the Limitation value increases.`

Currently RAR is only used when a power is activated (turned on).  We should check for `Must be made each Phase/use` modifier to instead make the check on each use.

**Comment by Kamarathin** [comment]
Yeah, it's a suit of armor and the requires roll simulates that it doesn't cover every mm of the characters body (not using Hit Locations):

From Hero Designer: Hardened Discreet Chain Jumper: Resistant Protection (5 PD/5 ED), Hardened (+1/4) (19 Active Points); IIF (-1/4), Requires A Roll (14- roll; -1/4)
