### ISSUE TITLE
AID/DRAIN should default the power name to XMLID + CHARACTERISTIC/INPUT

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#482]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/1532d4d0-7e4e-4a60-80d4-95e943b20e04)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/e2e3e9e7-5361-471a-917b-a79fbfd12a39)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/7cd851c6-bfca-43b4-b73e-9b732e3da462)

**Comment by phBalance** [comment]
As of 3.0.54 it is kludged in there like the previous version
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/f2f52e7a-0e04-45c8-999c-5d0f30285003)
