### ISSUE TITLE
BACKGROUND no longer uploads

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#483]
I suspect the BACKGROUND data is in the actor data, but the actor sheet is pointing at the wrong/old data structure.  Likely been an issue since the data restructure.  Likely similar issue with PERSONALITY, QUOTE, TACTICS, etc.

**Comment by aeauseth** [comment]
Moved to system.CHARACTER.CHARACTER_INFO.

**Comment by phBalance** [comment]
resolved by #517
