### ISSUE TITLE
DRAIN "into" description is odd

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#484]
Drain 2d6 `into` SPD (20 Active Points); OAF (-1), OAF (-1), No STR Bonus (-1/2).  Is this a 5e TRANSFER leftover?  The word `into` should not be here.  Looks to be associated with (the yet to be release) 3.0.53 as this does not seem to be an issue with 3.0.52.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/ed8a4362-7bc1-4e5a-972d-c2e1c5eeb625)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/589f689d-d88d-45d6-a8e1-5669b954ad10)

**Comment by phBalance** [comment]
Ya. Probably my stuff. Looking at things closer there are few oddities in the descriptions of a few adjustment powers I'll have a look at.
