### ISSUE TITLE
Token Bars Cannot Be Changed

### ISSUE THREAD

**Issue by SteveKottong** [dmdorman/hero6e-foundryvtt#502]
I'm not sure if anyone has mentioned this, or even that it's a v2 problem and not an interaction with one of my other mods, but I thought it would be best to at least ask the community. My tokens look like this:
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/28658998/f3ab7210-2ec1-47f2-9096-935ee6b3cdef) 
even though I have Use Endurance toggled off in the settings. I can turn the bars on or off, but if I modify them in any way, the changes are simply ignored.

As you can see in the configuration, I can change things, but the only thing that ever functions properly is the Display Bars dropdown up top. I can turn the bars off, on, on with hover, etc. with no issues, but the Attribute and Data sections of all 3 bars cannot be changed.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/28658998/b42e3131-1889-4ff9-9c97-8940abfa91c0)

Do y'all think it's an issue with this mod or some unknown interaction or just another mod's issue entirely?

Thank you for your help in advance,
-S

**Comment by aeauseth** [comment]
This is a known issue.  Dev team has discussed removing 3rd bar all together and instead relying on BarBrawl module.

**Comment by SteveKottong** [comment]
Thank you for your reply. Have a great weekend!

**Comment by aeauseth** [comment]
Did some testing with [Bar Brawl](https://foundryvtt.com/packages/barbrawl) and it overrides the quirky 3rd bar issue.  Actually it overrides all the custom resource bars.  Which is this case is great.  I'm going to recommend to the dev team we leverage Bar Brawl in the future.

**Comment by aeauseth** [comment]
Example of what tokens could look like with  [Bar Brawl](https://foundryvtt.com/packages/barbrawl)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/97c579ec-1ee2-46f2-89fe-b4c52952eba0) ![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/dafe7ebb-988b-4e45-8cec-4b4f597c8f1c)

**Comment by aeauseth** [comment]
hero system bar no longer supported.  Use BarBrawl for custom resources.
