### ISSUE TITLE
Dice roll 3 (always succeeds) & 18 (always fails)

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#522]
A result of 3 (three ones) always hits or succeeds; a result of 18 (three sixes) always misses or fails.  The current system does not implement this.  Make sure to include Attack Roll, Skill Roll, Characteristic Roll, Perception Roll, etc.

Optional: The Gamemaster (GM) should consider giving a character some advantage when his player rolls a 3 (perhaps some extra dice of damage), and some disadvantage for rolling an 18 (perhaps reducing the character’s DCV for a Segment or two).

**Comment by phBalance** [comment]
characteristics now implement this ... the rest will come with time using the new roller.

**Comment by aeauseth** [comment]
Version 3.0.67
