### ISSUE TITLE
Powers in Multipower/EC?/List? in non Powers tab in confusing order

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#523]
There is no context that these powers are in a multipower and they are also not sorted in numerical order:

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/14915e09-11e7-4087-99cb-3c5d944106d7)

**Comment by aeauseth** [comment]
Adding a roll icon in the POWER tab (where the multipower is organized better) might be helpful for attacks. 

Click on the chat icon (send to chat) shows it is part of a multipower.  Perhaps the description preface on the ATTACK/DEFENSE tabs would work.

For many framework powers you can only have one (or a few) on at a time.  We don't currently check for max AP of a MP.  Should prevent turning on powers when the MP would exceed max AP.
