### ISSUE TITLE
Ability to choose where Endurance is used from

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#54]
The ability to set up multiple Endurance Reserves (named?). A  dropdown box with "Endurance" and any Endurance Reserves setup in the Power/Attack. You would select the END source it uses, defaulting to just "Endurance" (i.e. the END most characters use).

**Comment by aeauseth** [comment]
Hero Design does include USE_END_RESERVE="Yes" for powers that use an Endurance Reserve.  HD does not allow you to choose between 2 or more end reserves.  Multiple endurance reserves is unusual, but legal.  Will likely default to 1st end reserve, with ability to change in FoundryVTT.

![Screenshot 2023-06-17 103339](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/9fe8a547-41e7-4b78-823d-a3f5f46fed5a)

**Comment by aeauseth** [comment]
Endurance Reserves also have their own recovery.
