### ISSUE TITLE
Equipment Sheet is defaulting to Default Sheet, but not herosystem6e.HeroSystem6eItemSheet

### ISSUE THREAD

**Issue by jephkay23** [dmdorman/hero6e-foundryvtt#57]
Equipment window is blank and resetting the sheet has no effect. 
![image](https://user-images.githubusercontent.com/115002200/225271151-3b3032bd-3a22-4a98-8793-012c1ce4afc7.png)

**Comment by dmdorman** [comment]
I think I know what this is, should be an easy fix

**Comment by techogre** [comment]
Still happening in 2.1.1

**Comment by dmdorman** [comment]
should be fixed as of v2.1.2-alpha
