### ISSUE TITLE
Invisibility can't get turned on

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#570]
Would be useful to have a checkbox to enable. Even though we wouldn't have enhanced senses, it would track endurance use.

**Comment by aeauseth** [comment]
Also consider applying the built in invisibility status.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/2761c197-858d-406a-abca-edbb8507d2e0)

**Comment by phBalance** [comment]
Turned into a defensive power so we have the checkmark and ability to turn on and off. Will leave issue open to integrate the status effect with this power.

**Comment by aeauseth** [comment]
Resolved in 3.0.71.
