### ISSUE TITLE
PD/ED bought as power (or show as secondary defense) were not being used in defense calculations

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#571]

**Comment by aeauseth** [comment]
I think secondary characteristics should default to OFF (unchecked) when uploaded via HDC.  In this case the power for 5e clearly isn't working.  Need to check with both 5e & 6e.

**Comment by aeauseth** [comment]
Strangely the PD seems to work but the ED does not.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/3dd9f35b-356e-42c7-8471-191c79b2f2a0)

**Comment by phBalance** [comment]
Appears to have been resolved as a part of #560 which did a number of fixes for ActiveEffects and this is implemented as an active effect on PD and ED.
