### ISSUE TITLE
Darkness' description doesn't show the power name of Darkness anywhere

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#573]

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/7696c051-f104-49c9-b60b-9a9ec8a71a6d)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/24f1a544-79b9-4725-8f3d-aab4c6eac136)

Might be able to reuse portions of the invisibility description code.
