### ISSUE TITLE
Armor piercing not working

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#604]

**Comment by aeauseth** [comment]
I think AP was actually working.  The tags were just confusing.  The defense tags now show actual defenses, which are halved in the summary line.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/f7cc8d91-e453-455c-b9a4-d05134fe4a56)

**Comment by aeauseth** [comment]
Notice `rPDh1 +6` which is short hand for 6 points of Resistant Physical Defense Hardened x 1.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/904e3f28-4a01-48e3-929f-a390c31f3660)

**Comment by phBalance** [comment]
I guess we should consider adjusting these lines in the future to show the total defense and then the actual effective defense and then the net result.
