### ISSUE TITLE
When a Skill is listed in a power, is listed as a "NaN-" skill roll

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#62]
![error](https://user-images.githubusercontent.com/10929680/229225653-59d397d4-1381-4388-ab2b-0781528eec9d.png)
When a skill is added to a Power item, the skill is listed with "NaN-" in the skill value. The skill is listed correctly and works correctly in the normal Skills tab.

**Comment by techogre** [comment]
Update V2.1.1
Now new skills, manoeuvres, attacks, defence, and movement added to a power do not display in the power, but they do show up when the power is added.

**Comment by dmdorman** [comment]
I think going forward Upload .HDC will sort things into the item type they were. Since Foundry V10 doesn't support items within items, having all the item types under power and equipment type items made maintaining the code difficult.
