### ISSUE TITLE
AID vs HEALING

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#649]
This issue is around the fact that (known issue) healing shouldn't be allowed to raise characteristics above starting value (i.e. shouldn't adjust max).

**Comment by phBalance** [comment]
At the same time we should probably consider implementing a similar limitation for aid as is seemingly present for healing.
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/5c9389b5-f052-4d2a-b314-b6ca818af744)
