### ISSUE TITLE
Error when applying damage

### ISSUE THREAD

**Issue by zaksquatch** [dmdorman/hero6e-foundryvtt#665]
I'm not sure if I'm missing something simple or not.

New world. Foundry is up-to-date. I create a PC with a power that does damage. Target a NPC and roll the attack. Everything is good so far.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/22183675/d58ef573-5609-496b-856e-de1b2f114166)

However, when I hit Roll Damage, I get:

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/22183675/e03dabff-e90a-4640-9107-8f157db12b54)

With the error in the console being:

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/22183675/6a6b074e-62ec-4b97-8864-ac50e41a5cae)

This a self-hosted install if that matters.

**Comment by phBalance** [comment]
@zaksquatch, as debugged via discord it appears this was a Foundry problem as your Foundry reinstall seems to have resolved things. Closing.
