### ISSUE TITLE
My game times out and dies when running to 3.0.55 or 3.0.56

### ISSUE THREAD

**Issue by rivethead42** [dmdorman/hero6e-foundryvtt#696]
I first ran into this when I upgraded to the 3.0.55 release and its still happening when I tried 3.0.56. Everything starts off fine with the join screen. But as soon as I log into the game is were everything falls apart. Now I have a lot of game assets loaded in. I practically have the entire Fantasy Bestiary added to the game along with a bunch of custom NPCs. This hasn't been an issue in the past until now. I figured maybe it was having issues converting the assets. So I spent the morning recreating everything. No issues. All the scenes, NPCs and players for the session were loaded in and I was good to go for the evening. However, everything fell apart when I tried to enter combat and the game just died. After restarting Foundry myself and my players were able to get the join screen, but upon entering the game we would get the blank screen and eventually the game would timeout.

After rolling back the game world to 3.0.54.2 and restoring from my latest backup the game was completely functional without any issues and I was able to complete the session. Has anyone else run into this problem? I've included several screenshots and it looks like the issue might be with socket.io. 

If there is any other information I can provide let me know.

![join screen](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/02f0a6b2-8a17-4ccf-81a6-a13cce1f81b0)
![join screen 2](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/f88f6580-2a6e-4499-acf3-597a9ac4cf7b)
![game1](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/8711445e-cdb4-4e14-ba1d-985d1787268c)
![game2](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/b0110b97-236f-4eb3-b8d1-92929b649349)
![game3](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/6fc510bb-bf2b-40de-aa05-c4b784ad3af7)
![game4](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/45b2c7e8-e2c8-456b-aa2d-615561b94f6f)
![game5](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/57b5d09a-e927-4baa-a088-779e01a83dcd)

**Comment by phBalance** [comment]
It's _possible_ this is related to changes that we made in the combat tracker in 3.0.55. We tried to fix them in 3.0.56 but we believe that we missed some cases. We have a 3.0.57 brewing in the pipeline - you can get it if you checkout the git repo with the 3.0.57 tag or wait until ~tomorrow for the official publish.

If, however, that's not the issue then I might need to get a copy of your world to try it on my system as the provided information isn't making anything jump out at me. I don't believe that we had any migration actions required between 3.0.54.2 and 3.0.55 which is why I'm guessing at the combat tracker.

Sorry about that and thanks for the report!

**Comment by rivethead42** [comment]
I can wait a day and let you know tomorrow. BTW you guys have been doing a great job with the system. I've been using it for close to a year and it's lightyears better than the alpha I started with.

**Comment by phBalance** [comment]
Fantastic. Sorry about the problem, but thanks again for the bug report! And hello to the future (3.0.75 isn't out yet, but 3.0.57 just came out ;)

**Comment by rivethead42** [comment]
Trust me you are making my life as a GM so much easier. My last game I was using Roll20 and tracking everything on paper because they didn't really have support for Hero v5. This was before we switched to v6 last year. Yeah I'm a bit of a holdout. lol
