### ISSUE TITLE
COMPOUND power with characteristics only does not load correctly

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#711]
Characteristics in a COMPOUNDPOWER do not have the POWER XML tag - they have a tag name of the characteristic. The code crashes: see `actor.js:1290` for instance. Other places in the code need to be fixed as well.

Additionally the characteristics in the compound power are not added.

**Comment by aeauseth** [comment]
Still issues with descriptions showing the 1) in the SKILLS and DEFENSE tabs. Also the layout of a compound power within a framework is odd, better indenting? HD combines the entire compound power description into a single line, which we are unlikely to do as keeping each item separate seems easier to deal with.
