### ISSUE TITLE
Ranged advantage not implemented.  Power incorrectly shows no range.

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#728]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/02acd235-9102-4a9b-b1d3-2f87b413aeb4)

**Comment by phBalance** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/7d9a761f-c452-4869-bdfc-038b23c0a017)
