### ISSUE TITLE
Combat tracker errors (3.0.58)

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#736]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/c45c1365-c0ea-496a-9701-5de92663f52a)

another error:

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/f853a75d-639a-4d6e-acdc-933b10c3fa44)

**Comment by aeauseth** [comment]
I was able to get errors by adding a token to the combat tracker, then deleting the actor from the sidebar, so issue is likely when there is a token, but missing actor.

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/b2a6a424-4a17-4277-b6ed-1a9aeff7c1dc)

**Comment by aeauseth** [comment]
Changing SPD might trigger issue.

**Comment by aeauseth** [comment]
Changing Initiative to be DEX or EGO + SPD/100 + INT/1000.
