### ISSUE TITLE
User Guide Needed

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#737]
Had an issue that I helped debug that points towards the fact that we could use a user guide so that people understand how to:
* create an HDC that will work with the system
* walk through how to run a combat (selecting characters, selecting target, etc)

**Comment by aeauseth** [comment]
Agreed, perhaps several short YouTube videos.

**Comment by aeauseth** [comment]
https://www.youtube.com/channel/UCcmq0WFFNZNhRSGwuEHOgRg
