### ISSUE TITLE
Adding token to initiative sometimes throws error in console

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#76]
Despite the error, the token still gets added to initiative tracker.  Most reproducible by deleting all encounters, then adding a token to the combat tracker,
 
![Screenshot 2023-05-12 175905](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/e602fe06-35cc-4631-b4ed-52aac409d09e)

**Comment by dmdorman** [comment]
Combat Tracker entries for stuff like Lightning Reflexes was missing a combatant ID. Should be fixed in the next release. To check if this is working try modifying a combatant from a Lightning Reflexes entry on the Combat Tracker.

**Comment by aeauseth** [comment]
![Screenshot 2023-05-28 155722](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/2d1f2303-e62d-4659-b5be-186189cc4143)
