### ISSUE TITLE
Skills purchased as powers are missing roll icon on POWERS tab and description doesn't show roll target

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#766]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/36d34acd-e357-43ce-8628-446e9d9eaf8d)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/99c20041-e827-40af-99ac-fc107068c62d)

**Comment by phBalance** [comment]
Roll can now be initiated from the powers tab.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/7a34c891-e085-41b2-a204-45fd93e4b358)
