### ISSUE TITLE
Invalid permissions with chat messages (Forge)

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#825]
These error messages are likely occurring when damage is being applied by the GM. The GM does not see this message but all players see it and the UI error that is generated. This is on forget for what it's worth.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/1287600c-84a7-4df3-b108-5f85ea2fc680)

**Comment by aeauseth** [comment]
https://discord.com/channels/687213225225355296/694659543052976268/1215863102273491004 suggests it is related to Simple Calendar and an update fixes it.

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/acde33d5-4c8d-4f89-9b7e-819408b407f7)

**Comment by aeauseth** [comment]
https://github.com/vigoren/foundryvtt-simple-calendar/issues/586

**Comment by phBalance** [comment]
Seems to have resolved the issue. Thanks for tracking down the cause @aeauseth!
