### ISSUE TITLE
Heroic Action Points

### ISSUE THREAD

**Issue by phBalance** [dmdorman/hero6e-foundryvtt#844]
Asked about on discord:

6e book 2 pg 287, but no mention in 5e, describe this optional rule. Slightly related to the Luck power.

Would probably require the ability for either character or the GM to generate Heroic Action Points (HAPs) for the PCs and NPC. Would also require the ability for the GM to clear out everyone's HAPs at the end of a session. Would need to provide a way to modify to-hit rolls, skill rolls,  damage pre application, etc by potentially both attacker and defender.

Seems like quite a bit of work for an optional rule. Probably lower down on the priority list.

**Comment by aeauseth** [comment]
Perhaps a place to track HAP would be sufficient as a starting point?  I agree full automation seems like a lot of work.  Juxtapozbliss just wanted a slot to manually track it.

**Comment by phBalance** [comment]
A quick and dirty way would be to add a custom power/skill/whatever and track it in that using LEVELS or CHARGES. This, however, wouldn't survive a reimporting the character's HDC.

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/b33f0eea-7614-4d7e-8538-c8d1da37bb23)

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/12593b61-1d80-45ed-b775-7307dcb3b122)

**Comment by phBalance** [comment]
A manual tracking solution has been implemented in #871 and it's likely all we'll do for the time being.
