### ISSUE TITLE
All damage gets through with a penetrating attack

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#851]
When using a penetrating attack all of the damage is being applied. The damage rolled for the attack is 16 Body and 48 Stun. The Girallon has 5 resistant ED and 6 normal ED. Because the attack doesn't block all of the damage the Girallon should take 11 Body and 37 Stun. However all of the damage is being applied bypassing it's defenses.

<img width="232" alt="pentrating 1" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/c38965df-d3ec-45ef-9d7a-3d7b02cdf7d2">

<img width="223" alt="pentrating 2" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/d489e56f-2229-41e5-8639-bf2e05e74255">

<img width="80" alt="pentrating 3" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/332460cf-1b58-4b55-9794-b8acb6f72c93">

**Comment by aeauseth** [comment]
Penetrating works for non-killing attacks.  Not working for killing attacks.  We are not calculating the "normal body" of the "body of the killing dice".  Confused yet?  Likely resolved in HeroRoller.

**Comment by tthomsen** [comment]
@aeauseth I'm pretty familiar with the rules on penetrating attacks so I follow you. Also what is HeroRoller, is this a new add-on module?

**Comment by phBalance** [comment]
@tthomsen, `HeroRoller` is our new class/chunk of code that handles abstracting most of the crazy complicated rules for dice rolls. It's part of the system that lives under the hood.
