### ISSUE TITLE
Some minor issues with custom skill after Release 3.0.59

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#852]
I use a lot of custom skills for casting magic in my fantasy campaign. Release 3.0.60 has introduced a few bugs. There was an issue with the custom skill not being found and automatically failing the roll when a spell was cast. That issue seems to have been fixed with release 3.0.62.2. However, custom skills are not appearing correctly on the character sheet.

Release 3.0.59
<img width="547" alt="Custom Skill" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/d8a8ee3b-e98f-4708-af99-6a4cbd902b80">
<img width="434" alt="Custom Skill 2" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/f92e65a3-f562-4223-bef3-406df0955171">

Post Release 3.0.59
<img width="558" alt="Screenshot 2024-03-17 111017" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/7be0211e-f798-453c-98d2-8d58b2c7bbe4">
<img width="429" alt="Custom Skill 3" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/2f8f9489-b98a-4a5e-96d9-670ee7759f44">
<img width="229" alt="Custom Skill 4" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/d582f789-4b62-491e-90d5-e859c774c6e1">

**Comment by phBalance** [comment]
The lack of custom skills support is showing here as my changes to the power list has removed some kludges that were apparently still required.

**Comment by aeauseth** [comment]
```xml
 <SKILL XMLID="CUSTOMSKILL" ID="1710723167067" BASECOST="0.0" LEVELS="1" ALIAS="Custom Skill" POSITION="0" MULTIPLIER="1.0" GRAPHIC="Burst" COLOR="255 255 255" SFX="Default" SHOW_ACTIVE_COST="Yes" INCLUDE_NOTES_IN_PRINTOUT="Yes" NAME="Faith" CHARACTERISTIC="GENERAL" FAMILIARITY="No" PROFICIENCY="No" LEVELSONLY="No" ROLL="1">
```

**Comment by aeauseth** [comment]
@tthomsen Looks like CHARACTERISTIC in Hero Designer is not supported (considered GENERAL).  The in game editor mistakenly lets you modify custom skill CHARACTERISTIC.  To get a 17- you will have to set the ROLL to 17 in Hero Designer.  

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/a437381b-e00e-493b-b360-44e42df1b2d2)

Alternatively you can rename/reskin an existing skill (like profession), which would allow you to use your EGO in your skill roll.  Then custom adders to tweak costs (if necessary).

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/0ea7bc2e-a425-4702-8f90-39be31325ab3)

**Comment by aeauseth** [comment]
#854 resolves the ability to make CUSTOMSKILL rolls.  However, the item-sheet shows LEVELS, but should be using ROLL internally.  COST is also likely wrong.  Should remove ability to change CHARACTERISTIC/TRAINING used.

**Comment by aeauseth** [comment]
@tthomsen also note that the item/skill header includes the version number, which is VERY handy when making bug reports.  Thanks for including that in the screen shots.

**Comment by aeauseth** [comment]
@tthomsen 3.0.63 includes a fix for the ROLL.  Does not resolve issues with the skill sheet.

**Comment by tthomsen** [comment]
@aeauseth thanks for letting me know about using the professional skill. It didn't occur to me to use that.

**Comment by tthomsen** [comment]
@aeauseth just tried using the professional skill for Faith and it worked perfectly. One thing I did notice was if the limitation is Requires A Roll (Skill roll, -1 per 20 Active Points modifier; Faith; -1/4) it will apply the penalty correctly to the skill roll. However, the -1/2 limitation doesn't apply the -1 per 10 Active Points penalty to the skill roll.
