### ISSUE TITLE
Manually added attacks break things

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#856]
Suspect player used "Add attack".   This is a legacy feature that we should probably remove "Add attack", "Add defense", Add Skill", etc  at some point.  The item.system.XMLID is undefined and so are all the other HD XML props, which are basically required with newer code base.  Specifically the migration throws lots of warnings.  Also some when actor sheets are opened.

Consider adding XMLID = "CUSTOMATTACK" for attack items missing XMLID.  This should at least provide basic support for migrations and opening actor/item sheets. 

- The STR items can be reproduced with STRIKE maneuver and modifying effective STR.
- The KNOCKBACK needs to be supported in the attack/damage chain.  Even this hack as an attack uses END, which isn't correct.  A checkbox on the attack to not use END would be pretty hacky.  Could also be reproduced with a STRIKE maneuver.  Create a HD power (HANDATTACK) for KNOCKBACK that costs no END, then import it.

Long term provide features that remove the need for these custom attacks.

Some issues are related to super old actors, we don't even have the system version number.  Suggest we skip migration on those actors, perhaps a single warning about re-uploading that actor.  Don't spam the GM during migrations.  Raymond in particular never deletes anything and migrations take several minutes as is.  The warnings make it take even longer.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/1033594b-f912-4c22-bfbd-221bfa7a8a18)

```js
{
    "name": "STR",
    "type": "attack",
    "system": {
        "description": "",
        "effect": "",
        "cost": 0,
        "modifiers": [],
        "hdcid": "",
        "parentid": "",
        "defense": "pd",
        "killing": false,
        "piercing": 0,
        "penetrating": 0,
        "advantages": 0,
        "dice": 43,
        "toHitMod": 0,
        "extraDice": "zero",
        "uses": "ocv",
        "targets": "dcv",
        "end": 0,
        "stunX": 0,
        "class": "physical",
        "areaOfEffect": {
            "type": "none",
            "value": 0,
            "width": 0,
            "height": 0
        },
        "stunBodyDamage": "stunbody",
        "ocv": null,
        "dcv": null,
        "knockbackMultiplier": "0",
        "usesStrength": false,
        "usesTk": false,
        "noHitLocations": false,
        "basePointsPlusAdders": null,
        "activePoints": 0,
        "realCost": "0",
        "charges": {
            "value": null,
            "max": null,
            "recoverable": false
        },
        "USE_END_RESERVE": false,
        "max": 0,
        "value": 0,
        "baseCost": 0,
        "activePointsDc": 0
    },
    "_id": "KxYsSS8d8dPZdCB3",
    "img": "icons/svg/sword.svg",
    "effects": [],
    "folder": null,
    "sort": 0,
    "ownership": {
        "default": 0,
        "vyaLXzFbhxhlGFym": 3
    },
    "flags": {},
    "_stats": {
        "systemId": "hero6efoundryvttv2",
        "systemVersion": "3.0.63",
        "coreVersion": "11.315",
        "createdTime": 1710643179051,
        "modifiedTime": 1710817013101,
        "lastModifiedBy": "wjwBVu3E3fGldQSo"
    }
}
```

**Comment by phBalance** [comment]
Closing. 3.0.64 provides warning messages to users and CHANGELOG.md entry.
