### ISSUE TITLE
Ranged Levels (PSL)

### ISSUE THREAD

**Issue by SteveKottong** [dmdorman/hero6e-foundryvtt#863]
Are PSLs implemented in this module yet? If they are, how can I set them up? Also, some weapons have range modifiers but in the HERO Designer they seem to be implemented as Compound Powers which I believe are not implemented.

If we have to manage them manually for now, that's cool. I just didn't want to overlook something obvious if it were there.

Thanks in advance,
-M

**Comment by aeauseth** [comment]
PSL are partially implemented, ranked a D in [FEATURES](https://github.com/dmdorman/hero6e-foundryvtt/blob/main/FEATURES.md).  You might get a popup during attacks to apply PSLs for OCV, but I don't believe range penalties are supported.  Compound powers aren't really related to PSLs.  Currently compound powers are treated as a an simple organizational mechanism, there is no rules based relationship.

PSLs in Hero Designer are pretty vague.  Devs will need to find a way to structure PSL's so they can be applied in the right places via automation.

**Comment by aeauseth** [comment]
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/00f2201a-a96d-40a7-8298-4c80f7d245e1)
