### ISSUE TITLE
New dev startup: local branch construction

### ISSUE THREAD

**Issue by coderodent-calfee** [dmdorman/hero6e-foundryvtt#880]
with Foundry installed and the appropriate directories created I did the following:

launched the foundry with  `node resources/app/main.js --dataPath=H:\projects\FoundryData`

Attempted to use the github addresses for installing the code in the repo: no dice
used `git clone https://github.com/dmdorman/hero6e-foundryvtt.git` to install the system to the local foundry data system directory: it was not recognized as installed

I then installed the current game rules. That gave me the current game rules.
I deleted the contents and cloned the main branch of the development repo into it.

> FoundryVTT | 2024-03-29 15:38:16 | [error] Metadata validation failed for system "hero6efoundryvttv2": The file "css/herosystem6e.css" included by system hero6efoundryvttv2 does not exist
> Error: Metadata validation failed for system "hero6efoundryvttv2": The file "css/herosystem6e.css" included by system hero6efoundryvttv2 does not exist
>     at PackageAssetField.initialize (file:///H:/Foundry-Virtual-Tabletop/resources/app/dist/packages/package.mjs:1:1457)
>     at file:///H:/Foundry-Virtual-Tabletop/resources/app/common/data/fields.mjs:1010:40
>     at Array.map (<anonymous>)
>     at SetField.initialize (file:///H:/Foundry-Virtual-Tabletop/resources/app/common/data/fields.mjs:1010:18)
>     at SetField.initialize (file:///H:/Foundry-Virtual-Tabletop/resources/app/common/data/fields.mjs:1090:26)
>     at System._initialize (file:///H:/Foundry-Virtual-Tabletop/resources/app/common/abstract/data.mjs:216:27)
>     at System._initialize (file:///H:/Foundry-Virtual-Tabletop/resources/app/dist/packages/package.mjs:1:3231)
>     at new DataModel (file:///H:/Foundry-Virtual-Tabletop/resources/app/common/abstract/data.mjs:63:10)
>     at new BasePackage (file:///H:/Foundry-Virtual-Tabletop/resources/app/common/packages/base-package.mjs:213:5)
>     at new ServerPackageMixin (file:///H:/Foundry-Virtual-Tabletop/resources/app/dist/packages/package.mjs:1:1680)

What finally worked was a hacky bit; installing the current rules and then _copying_ the contents of a cloned repo into that directory.

I'd rather not put a terrible hack into working documentation, and I suspect there is just something I don't know or understand to solve for this. Also I have a feeling this may put local work at risk when the installed rules get updated.

Comments are requested.

**Comment by phBalance** [comment]
Have a look at `CONTRIBUTING.md` and you'll see some suggestions. In particular the `Building the System` part might be of interest to you: https://github.com/dmdorman/hero6e-foundryvtt/blob/main/CONTRIBUTING.md#building-the-system .

Sounds like you didn't do `npm ci` to install the packages required to build a functioning system nor did you do `npm run build` to actually build the functioning system.

Let me know if that doesn't get you going.

**Comment by aeauseth** [comment]
@coderodent-calfee Please join us on our discord server: https://discord.gg/acQGZR5u

**Comment by phBalance** [comment]
@coderodent-calfee please let me know if the changes made to `CONTRIBUTING.md` are, in your estimation, a sufficient improvement to make it easier for the next person.

**Comment by coderodent-calfee** [comment]
Yes, I was not able to duplicate my problems; Foundry won't give you specifics on dependencies once you have installed a module, is just says they are not met. But I unloaded and reloaded the add-on and there was the warning clear as day. 

I must have missed it the first time though.
It's always helpful to have additional text though, and it's easy to add.

Yes it is a sufficient improvement.
