### ISSUE TITLE
New dev setup: drag-ruler

### ISSUE THREAD

**Issue by coderodent-calfee** [dmdorman/hero6e-foundryvtt#881]
I had difficulty setting up the drag ruler. All of this are from bug/failures in code outside of the hero system stuff; but a simple workaround is available by annotating the setup.

The drag-ruler needs `socketlib` to function. There is no display to the GM that this is the case (there are warnings in the drag-ruler code, but they don't show to the user, nor in the console: that's a bug on Forge code). Drag-Ruler docs also don't make mention of the dependency (that's a bug on drag-ruler side). 

For Heroes, we can put this in the dev docs and move forward.

FWIW: if you have socketlib and drag-ruler, drag ruler _does_ tell you to enable socketlib.

**Comment by phBalance** [comment]
When you go to enable the `Drag Ruler` module, in manage modules, it will tell you that it has a dependency and ask you to install & enable it. Feel free to update the documentation in `CONTRIBUTING.md` or `README.md` to make this more clear.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/29824554/a420674b-2505-45ec-bce5-63c517e161c2)

**Comment by aeauseth** [comment]
This really isn't a CONTRIBUTING issues, all GM's will experience this.  Could include in the README.

**Comment by aeauseth** [comment]
Is this specific to FORGE hosting? I've never had this issue with local hosting.

**Comment by coderodent-calfee** [comment]
Weirdly did not see that warning earlier, but now I do.
