### ISSUE TITLE
6e Boostable charges not working

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#902]
When a value (the number of charges to boost with?) is entered in the bootable box, the attack roll is not rolled, and the bootable value is reset to zero.

Steps to reproduce:

1. Create a character with 1d6 Blast with 4 charges, and the Boostable advantage.
2. Attack a target character.
3. In the to hit dialogue change the Boostable to a 1. I assume this is supposed to use 1 extra charge.
4. When you click on the "Roll to Hit" button, the Boostable value is reset to 0 and there is no other change.

**Comment by aeauseth** [comment]
Works, but the boostable charge box clears when select new tokens or otherwise gets refreshed.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/484e9320-51ba-4fe1-9b5e-7049eb8be935)
