### ISSUE TITLE
hero6efoundryvttv2 is hard coded in several places

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#932]
If you change the id in system.json lots of things break.  Should use game.system.id instead.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/ff129ca5-2d9e-46b8-b480-2a9aae3cd432)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/8e16bacf-1c1b-4857-8949-0b19ed0300e4)

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/540822ac-3e4e-40c0-80f5-888df4cd92ca)

**Comment by phBalance** [comment]
This is resolved by #938
