### ISSUE TITLE
Melee weapons and min STR

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#971]
I'm not sure if this is a bug or a feature that hasn't been implemented yet. Weapons with a STR min limitation still apply the full STR of the character to the attack. For example, I have a character with a 30 STR that wields a great mace with a STR min of 15 that is a 2d6 HKA. With STR it should only do 3d6. However, it is setting the damage to 4d6. I am able to adjust the damage after importing the character so it's not a huge deal but it does get kind of annoying when there are multiple weapons on the sheet.

Attacks tab:
<img width="592" alt="melee weapons and STR" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/ed06f548-3fdb-4597-bf30-6419a87be4b1">

Weapon info:
<img width="451" alt="melee weapons and STR2" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/5940fd82-3731-4aad-b052-1e6c9eafacad">

Thanks as always!

**Comment by aeauseth** [comment]
This shouldn't be too hard to implement.

**Comment by aeauseth** [comment]
See also #127.

**Comment by aeauseth** [comment]
@tthomsen In Heroic campaigns, STR costs 1 END per 5 STR rather than 1 END per 10; END costs for Powers do not
change.  Currently we have no mechanism to reduce STR END cost for heroic campaigns.  Is this an issue for your game?

**Comment by tthomsen** [comment]
Nah that should be fine. We can manually adjust any END costs.
