### ISSUE TITLE
Weaponmaster and Deadly Blow

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#972]
Are there plans to implement Weaponmaster and Deadly Blow with attacks? It would be great if you could select the attacks they apply to like how combat skill levels are implemented.

Something similar to this:
<img width="443" alt="combat skill level selection" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/b93be46e-9482-4515-949a-b6a814708f7c">

**Comment by aeauseth** [comment]
The +3DC is pretty straight forward.  Need to discuss with @phBalance about the conditional part as I recall concerns about how conditional defenses are implemented.

**Comment by rivethead42** [comment]
Maybe when the attack roll is being made they can check a box.

**Comment by aeauseth** [comment]
@phBalance you OK with conditional attack bonuses in the same theme as conditional defenses?  
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/6dee3897-3236-497e-9e5c-c4380e36b250)

**Comment by aeauseth** [comment]
I'm working on an alternate (better?) way of dealing with powers that only apply to a subset of attacks.  Attacks with checkboxes are converted to custom adders.  This should allow people to use custom adders in HD, which we can parse in FoundryVTT.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/f187aece-7255-445d-a0d8-0ac9861c77e3)
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/991360a4-d93a-4f4b-ae13-3a82357b96d7)

**Comment by aeauseth** [comment]
Initial support for WeaponMaster.  Have not reviewed costs. 
![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/0fe1628d-6d43-40b4-a18a-bcbcadf71b54)

**Comment by aeauseth** [comment]
Example of Deadly Blow conditional attack bonus:

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/aa70098f-3ff8-46b5-8f20-0baee5f26ac8)
