### ISSUE TITLE
Personal immunity not be taken into consideration

### ISSUE THREAD

**Issue by tthomsen** [dmdorman/hero6e-foundryvtt#973]
Several of my characters have whirlwind attack from the fantasy book. The attack is defined with the personal immunity advantage. However, when the attack is executed it includes the character wielding the attack.

Attack placement.
<img width="576" alt="whirlwind attack1" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/aa1f2a4b-3c48-40ad-8709-038b2ba460ee">

Attack card:
<img width="251" alt="whirlwind attack2" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/b2986a82-c409-4fa8-b930-848df8e1e4c0">

Attack details:
<img width="450" alt="whirlwind attack3" src="https://github.com/dmdorman/hero6e-foundryvtt/assets/277447/c466aebc-6522-437b-9d28-5b76ef5628eb">

**Comment by aeauseth** [comment]
Should be easy to implement personal immunity with AOE attacks.

**Comment by rivethead42** [comment]
Can confirm Shirt-T works fine. Sorry I just realized I'm logged in using my other GitHub account 

![Whirlwind attack](https://github.com/dmdorman/hero6e-foundryvtt/assets/25353751/31f6e62f-1d49-4189-b4b1-79de3fe03210)

**Comment by aeauseth** [comment]
AOE template no longer automatically targets token with PERSONALIMMUNITY.  Actors with PERSONALIMMUNITY are also removed during ROLL DAMAGE routine, although this would be an unusual workflow for a typical attack as PERSONALIMMUNITY is largely associated with AOE.
